const seedProducts=[{id:1,name:"Смартфон Redmi Note",category:"Техника",price:15990,seller:"ТехноДом",location:"Красногвардейский район",rating:4.9,image:"https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",description:"Современный смартфон для повседневных задач.",unit:"1 шт"},{id:2,name:"Стиральный порошок Ariel",category:"Бытовая химия",price:890,seller:"Чистый Дом",location:"Красногвардейский район",rating:4.8,image:"https://images.unsplash.com/photo-1583947582886-f40ec95dd752?auto=format&fit=crop&w=1200&q=80",description:"Эффективный порошок для белого и цветного белья.",unit:"3 кг"},{id:3,name:"Мужская куртка",category:"Одежда",price:3490,seller:"Магазин Одежды",location:"Красногвардейский район",rating:4.7,image:"https://images.unsplash.com/photo-1523398002811-999ca8dec234?auto=format&fit=crop&w=1200&q=80",description:"Удобная и тёплая куртка на каждый день.",unit:"Размер M-XL"},{id:4,name:"Садовая лопата",category:"Огород",price:650,seller:"Огородник",location:"Красногвардейский район",rating:4.9,image:"https://images.unsplash.com/photo-1617576683096-00fc8eecb3af?auto=format&fit=crop&w=1200&q=80",description:"Прочная лопата для сада и огорода.",unit:"1 шт"},{id:5,name:"Набор кастрюль",category:"Кухня",price:4990,seller:"Кухня Плюс",location:"Красногвардейский район",rating:5,image:"https://images.unsplash.com/photo-1584990347449-a50f8d4f7f40?auto=format&fit=crop&w=1200&q=80",description:"Набор кастрюль для ежедневной готовки.",unit:"5 предметов"},{id:6,name:"Органайзер для дома",category:"Дом",price:1290,seller:"УютМаркет",location:"Красногвардейский район",rating:4.8,image:"https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",description:"Практичный органайзер для хранения вещей.",unit:"1 комплект"}];
const get=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d)); const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function initData(){if(!localStorage.getItem('dm_products'))set('dm_products',seedProducts); if(!localStorage.getItem('dm_favorites'))set('dm_favorites',[]); if(!localStorage.getItem('dm_cart'))set('dm_cart',[]); if(!localStorage.getItem('dm_orders'))set('dm_orders',[]);}
const products=()=>get('dm_products',seedProducts), cart=()=>get('dm_cart',[]), favorites=()=>get('dm_favorites',[]), orders=()=>get('dm_orders',[]);
function saveProducts(v){set('dm_products',v)} function saveCart(v){set('dm_cart',v);updateCartCount()} function saveFavorites(v){set('dm_favorites',v)} function saveOrders(v){set('dm_orders',v)}
function updateCartCount(){document.querySelectorAll('#cart-count').forEach(el=>el.textContent=cart().reduce((s,i)=>s+i.qty,0));}
function addToCart(id){const p=products().find(x=>x.id===id); let c=cart(); const e=c.find(x=>x.id===id); if(e)e.qty++; else c.push({...p,qty:1}); saveCart(c); alert('Товар добавлен в корзину!'); renderCart();}
function toggleFavorite(id){let f=favorites(); f=f.includes(id)?f.filter(x=>x!==id):[...f,id]; saveFavorites(f); renderFavorites(); renderCatalog(); renderProducts('featured-products',products(),6);}
function deleteProduct(id){saveProducts(products().filter(x=>x.id!==id)); saveCart(cart().filter(x=>x!==id)); saveFavorites(favorites().filter(x=>x!==id)); location.reload();}
function productCard(p){const fav=favorites().includes(p.id); return `<div class="product-card"><img src="${p.image}" alt="${p.name}"><div class="product-body"><div class="product-top"><div><h3>${p.name}</h3><p class="muted">${p.seller}</p></div><span class="badge">${p.category}</span></div><p class="muted">${p.description}</p><div class="meta"><span>📍 ${p.location}</span><span>⭐ ${p.rating}</span><span>📦 ${p.unit}</span></div><div class="price-row"><div class="price">${p.price} ₽</div></div><div class="price-row"><button class="btn btn-outline" onclick="openProduct(${p.id})">Подробнее</button><button class="btn" onclick="addToCart(${p.id})">В корзину</button></div><div class="price-row"><button class="btn btn-outline" onclick="toggleFavorite(${p.id})">${fav?'💔 Убрать':'❤️ В избранное'}</button></div></div></div>`}
function renderProducts(id,list,limit=null){const box=document.getElementById(id); if(!box)return; box.innerHTML=(limit?list.slice(0,limit):list).map(productCard).join('');}
function renderCatalog(){const box=document.getElementById('catalog-products'); if(!box)return; const search=document.getElementById('search-input'); const filter=document.getElementById('category-filter'); function apply(){const q=(search?.value||'').toLowerCase(), c=filter?.value||'all'; const arr=products().filter(p=>[p.name,p.description,p.seller,p.location].join(' ').toLowerCase().includes(q)&&(c==='all'||p.category===c)); box.innerHTML=arr.length?arr.map(productCard).join(''):'<div class="card"><h3>Ничего не найдено</h3></div>';} search?.addEventListener('input',apply); filter?.addEventListener('change',apply); apply();}
function renderFavorites(){const box=document.getElementById('favorites-products'); if(!box)return; const favs=products().filter(p=>favorites().includes(p.id)); box.innerHTML=favs.length?favs.map(productCard).join(''):'<div class="card"><h3>Избранное пусто</h3></div>';}
function renderCart(){const items=document.getElementById('cart-items'), totalBox=document.getElementById('cart-total'); if(!items||!totalBox)return; const c=cart(); if(!c.length){items.innerHTML='<div class="card"><h3>Корзина пуста</h3></div>'; totalBox.innerHTML='<h3>Итого: 0 ₽</h3>'; return;} items.innerHTML=c.map(i=>`<div class="cart-item"><div><h3>${i.name}</h3><p class="muted">${i.seller} • ${i.unit}</p><p>${i.price} ₽ × ${i.qty} = <strong>${i.price*i.qty} ₽</strong></p></div><div class="qty"><button onclick="changeQty(${i.id},-1)">−</button><span>${i.qty}</span><button onclick="changeQty(${i.id},1)">+</button><button class="icon-btn danger" onclick="removeFromCart(${i.id})">🗑</button></div></div>`).join(''); const total=c.reduce((s,i)=>s+i.price*i.qty,0); totalBox.innerHTML=`<h3>Итого: ${total} ₽</h3><p class="muted">После оформления заявка попадёт в админку.</p><div style="display:flex;flex-direction:column;gap:10px;margin-top:16px"><button class="btn" onclick="openCheckout()">Оформить заказ</button></div>`;}
function changeQty(id,d){saveCart(cart().map(i=>i.id===id?{...i,qty:Math.max(1,i.qty+d)}:i)); renderCart()} function removeFromCart(id){saveCart(cart().filter(i=>i.id!==id)); renderCart()} function clearCart(){saveCart([]); renderCart()}
function openProduct(id){const p=products().find(x=>x.id===id), m=document.getElementById('product-modal'), b=document.getElementById('modal-body'); if(!p||!m||!b)return; b.innerHTML=`<div class="modal-grid"><img src="${p.image}" alt="${p.name}"><div><span class="badge">${p.category}</span><h2 style="margin:12px 0">${p.name}</h2><p class="muted" style="margin-bottom:14px">${p.description}</p><p><strong>Продавец:</strong> ${p.seller}</p><p><strong>Локация:</strong> ${p.location}</p><p><strong>Комплект:</strong> ${p.unit}</p><div class="price-row" style="margin-top:20px"><div class="price">${p.price} ₽</div><button class="btn" onclick="addToCart(${p.id})">Добавить в корзину</button></div></div></div>`; m.classList.remove('hidden')}
function closeModal(){document.getElementById('product-modal')?.classList.add('hidden')} function openCheckout(){document.getElementById('checkout-modal')?.classList.remove('hidden')} function closeCheckout(){document.getElementById('checkout-modal')?.classList.add('hidden')}
function setupForms(){document.getElementById('checkout-form')?.addEventListener('submit',e=>{e.preventDefault(); const c=cart(); const total=c.reduce((s,i)=>s+i.price*i.qty,0); const order={name:document.getElementById('customer-name').value,phone:document.getElementById('customer-phone').value,address:document.getElementById('customer-address').value,comment:document.getElementById('customer-comment').value,items:c,total:total,date:new Date().toLocaleString('ru-RU')}; const arr=orders(); arr.unshift(order); saveOrders(arr); alert('Спасибо! Заявка отправлена администратору.'); saveCart([]); closeCheckout(); renderCart(); e.target.reset();}); document.getElementById('seller-form')?.addEventListener('submit',e=>{e.preventDefault(); alert('Профиль продавца сохранён!'); e.target.reset();}); document.getElementById('product-form')?.addEventListener('submit',e=>{e.preventDefault(); const p={id:Date.now(),name:name.value,price:Number(price.value),seller:seller.value,location:location.value,image:image.value,unit:unit.value,category:category.value,description:description.value,rating:5}; const arr=products(); arr.unshift(p); saveProducts(arr); alert('Товар добавлен!'); e.target.reset(); renderSellerProducts(); renderCatalog();});}
function renderSellerProducts(){const box=document.getElementById('seller-products'); if(!box)return; box.innerHTML=products().map(i=>`<div class="seller-item"><div><strong>${i.name}</strong><p class="muted">${i.price} ₽ • ${i.category}</p></div><button class="icon-btn danger" onclick="deleteProduct(${i.id})">🗑</button></div>`).join('')}
function renderAdmin(){const p=products(), f=favorites(), c=cart(); const a=document.getElementById('admin-products-count'), b=document.getElementById('admin-favorites-count'), d=document.getElementById('admin-cart-count'); if(a)a.textContent=p.length; if(b)b.textContent=f.length; if(d)d.textContent=c.reduce((s,i)=>s+i.qty,0); const box=document.getElementById('admin-products'); if(box) box.innerHTML=p.map(i=>`<div class="seller-item"><div><strong>${i.name}</strong><p class="muted">${i.seller} • ${i.price} ₽</p></div><button class="icon-btn danger" onclick="deleteProduct(${i.id})">🗑</button></div>`).join(''); const obox=document.getElementById('admin-orders'); if(obox) obox.innerHTML=orders().length?orders().map((o,idx)=>`<div class="seller-item"><div><strong>Заявка #${idx+1}</strong><p class="muted">${o.name} • ${o.phone}</p><p>${o.address}</p><p class="muted">${o.comment || 'Без комментария'}</p><p><strong>Товары:</strong> ${o.items.map(i=>`${i.name} (${i.qty} шт.)`).join(', ')}</p><p><strong>Сумма:</strong> ${o.total} ₽</p><p class="muted">${o.date}</p></div><button class="icon-btn danger" onclick="deleteOrder(${idx})">🗑</button></div>`).join(''):'<p class="muted">Заявок пока нет.</p>';}
function deleteOrder(index){const arr=orders(); arr.splice(index,1); saveOrders(arr); location.reload();}
const ADMIN_PASSWORD = "3337333";
function isAdminUnlocked(){ return sessionStorage.getItem('dm_admin_unlocked') === 'yes'; }
function setupAdminAuth(){const form=document.getElementById('admin-login-form'); const lock=document.getElementById('admin-lock'); const panel=document.getElementById('admin-panel'); const msg=document.getElementById('admin-login-message'); if(!form||!lock||!panel)return; function sync(){if(isAdminUnlocked()){lock.classList.add('hidden'); panel.classList.remove('hidden'); renderAdmin();} else {lock.classList.remove('hidden'); panel.classList.add('hidden');}} form.addEventListener('submit',(e)=>{e.preventDefault(); const val=document.getElementById('admin-password').value.trim(); if(val===ADMIN_PASSWORD){sessionStorage.setItem('dm_admin_unlocked','yes'); if(msg) msg.textContent=''; sync();} else {if(msg) msg.textContent='Неверный пароль';}}); sync();}
function resetDemoData(){localStorage.removeItem('dm_products');localStorage.removeItem('dm_cart');localStorage.removeItem('dm_favorites');localStorage.removeItem('dm_orders');initData();location.reload()}
document.addEventListener('DOMContentLoaded',()=>{initData(); updateCartCount(); renderProducts('featured-products',products(),6); renderCatalog(); renderFavorites(); renderCart(); renderSellerProducts(); renderAdmin(); setupForms(); setupAdminAuth(); document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')}));});